name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CSS_AZ_SECRET }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        package: .

    - name: Configure App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              AZURE_FORM_RECOGNIZER_ENDPOINT="${{ secrets.AZURE_FORM_RECOGNIZER_ENDPOINT }}" \
              AZURE_FORM_RECOGNIZER_KEY="${{ secrets.AZURE_FORM_RECOGNIZER_KEY }}" \
              AZURE_SEARCH_SERVICE_NAME="${{ secrets.AZURE_SEARCH_SERVICE_NAME }}" \
              AZURE_SEARCH_API_KEY="${{ secrets.AZURE_SEARCH_API_KEY }}" \
              AZURE_SEARCH_INDEX_NAME="smartdoc-index" \
              AZURE_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              AZURE_STORAGE_CONTAINER_NAME="${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
              STREAMLIT_SERVER_PORT="8000" \
              STREAMLIT_SERVER_ADDRESS="0.0.0.0" \
              STREAMLIT_SERVER_HEADLESS="true" \
              STREAMLIT_BROWSER_GATHER_USAGE_STATS="false" \
              SCM_DO_BUILD_DURING_DEPLOYMENT="true" \
              ENABLE_ORYX_BUILD="true" \
              PYTHONPATH="/home/site/wwwroot"

    - name: Set startup command
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --startup-file "startup.py"

    - name: Restart Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

    - name: Get deployment URL
      run: |
        echo "Deployment completed successfully!"
        echo "Your app is available at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
